# Makefile demos

demo : 
	mkdir -p ../build/obj/demos
	#mkdir -p ../build/obj/demos/demo_template
	#$(MAKE) -C ./demo_template demo
	mkdir -p ../build/obj/demos/demo_vector_line
	$(MAKE) -C ./demo_vector_line demo
	mkdir -p ../build/obj/demos/demo_integral_gsl
	$(MAKE) -C ./demo_integral_gsl demo

